version: '2'

services:

  jenkins-master:
    container_name: jenkins-master
    image: prasantk/jenkins:lts
    group_add:
      - 998
    # ports:
    #   - 8080:8080
    #   - 50000:50000
    depends_on:
      - sonarqube
    environment:
      - VIRTUAL_HOST=jenkins.local
      - VIRTUAL_PORT=8080
    volumes:
      - /data/jenkins-master:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  jenkins-agent:
    image: vfarcic/jenkins-swarm-agent:18.04.01-1
    depends_on:
      - jenkins-master
    extra_hosts:
      - "staging.calculator.local:10.0.15.40"
      - "prod.calculator.local:10.0.15.40"
      - "staging.petclinic.local:10.0.15.40"
      - "prod.petclinic.local:10.0.15.40"
    environment:
      - COMMAND_OPTIONS=-master http://jenkins-master:8080 -username admin -password admin -labels docker-agent -executors 5
    volumes:
      - /data/jenkins-agent:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  sonarqubedb:
    image: postgres:10-alpine
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
    volumes:
      - /data/sonarqube/db-data:/var/lib/postgresql/data
    restart: always
  
  sonarqube:
    image: sonarqube:6.7.2-alpine
    # ports:
    #   - "9000:9000"
    depends_on:
      - sonarqubedb
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqubedb:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarqube
      - VIRTUAL_HOST=sonarqube.local
      - VIRTUAL_PORT=9000
    volumes:
      - /data/sonarqube/app-data:/opt/sonarqube/data
    restart: always

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always